/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dls102
 * @edited dpg5252
 * 
 */
public class TicTacToe_Application extends javax.swing.JFrame {

    /**
     * Creates new form TicTacToe_Application
     */
    public TicTacToe_Application() {
        initComponents();
        player = new EchoClient("localhost",10005, this);
        player.start();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        playerTextField = new javax.swing.JTextField();
        button1 = new javax.swing.JButton();
        button2 = new javax.swing.JButton();
        button3 = new javax.swing.JButton();
        button4 = new javax.swing.JButton();
        button5 = new javax.swing.JButton();
        button6 = new javax.swing.JButton();
        button7 = new javax.swing.JButton();
        button8 = new javax.swing.JButton();
        button9 = new javax.swing.JButton();
        button10 = new javax.swing.JButton();
        button11 = new javax.swing.JButton();
        button12 = new javax.swing.JButton();
        button13 = new javax.swing.JButton();
        button14 = new javax.swing.JButton();
        button15 = new javax.swing.JButton();
        winnerField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        playerTurnField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        yesButton = new javax.swing.JButton();
        noButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        button.setText("---");
        button.setMaximumSize(new java.awt.Dimension(60, 60));
        button.setMinimumSize(new java.awt.Dimension(60, 60));
        button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt);
            }
        });

        jLabel1.setText("Player:");

        button1.setText("---");
        button1.setMaximumSize(new java.awt.Dimension(60, 60));
        button1.setMinimumSize(new java.awt.Dimension(60, 60));
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        button2.setText("---");
        button2.setMaximumSize(new java.awt.Dimension(60, 60));
        button2.setMinimumSize(new java.awt.Dimension(60, 60));
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        button3.setText("---");
        button3.setMaximumSize(new java.awt.Dimension(60, 60));
        button3.setMinimumSize(new java.awt.Dimension(60, 60));
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });

        button4.setText("---");
        button4.setMaximumSize(new java.awt.Dimension(60, 60));
        button4.setMinimumSize(new java.awt.Dimension(60, 60));
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });

        button5.setText("---");
        button5.setMaximumSize(new java.awt.Dimension(60, 60));
        button5.setMinimumSize(new java.awt.Dimension(60, 60));
        button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button5ActionPerformed(evt);
            }
        });

        button6.setText("---");
        button6.setMaximumSize(new java.awt.Dimension(60, 60));
        button6.setMinimumSize(new java.awt.Dimension(60, 60));
        button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button6ActionPerformed(evt);
            }
        });

        button7.setText("---");
        button7.setMaximumSize(new java.awt.Dimension(60, 60));
        button7.setMinimumSize(new java.awt.Dimension(60, 60));
        button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button7ActionPerformed(evt);
            }
        });

        button8.setText("---");
        button8.setMaximumSize(new java.awt.Dimension(60, 60));
        button8.setMinimumSize(new java.awt.Dimension(60, 60));
        button8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button8ActionPerformed(evt);
            }
        });

        button9.setText("---");
        button9.setMaximumSize(new java.awt.Dimension(60, 60));
        button9.setMinimumSize(new java.awt.Dimension(60, 60));
        button9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button9ActionPerformed(evt);
            }
        });

        button10.setText("---");
        button10.setMaximumSize(new java.awt.Dimension(60, 60));
        button10.setMinimumSize(new java.awt.Dimension(60, 60));
        button10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button10ActionPerformed(evt);
            }
        });

        button11.setText("---");
        button11.setMaximumSize(new java.awt.Dimension(60, 60));
        button11.setMinimumSize(new java.awt.Dimension(60, 60));
        button11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button11ActionPerformed(evt);
            }
        });

        button12.setText("---");
        button12.setMaximumSize(new java.awt.Dimension(60, 60));
        button12.setMinimumSize(new java.awt.Dimension(60, 60));
        button12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button12ActionPerformed(evt);
            }
        });

        button13.setText("---");
        button13.setMaximumSize(new java.awt.Dimension(60, 60));
        button13.setMinimumSize(new java.awt.Dimension(60, 60));
        button13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button13ActionPerformed(evt);
            }
        });

        button14.setText("---");
        button14.setMaximumSize(new java.awt.Dimension(60, 60));
        button14.setMinimumSize(new java.awt.Dimension(60, 60));
        button14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button14ActionPerformed(evt);
            }
        });

        button15.setText("---");
        button15.setMaximumSize(new java.awt.Dimension(60, 60));
        button15.setMinimumSize(new java.awt.Dimension(60, 60));
        button15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button15ActionPerformed(evt);
            }
        });

        jLabel2.setText("Winner:");

        jLabel3.setText("Player's Turn:");

        jLabel4.setText("Play Again?");

        yesButton.setText("Yes");
        yesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesButtonActionPerformed(evt);
            }
        });

        noButton.setText("No");
        noButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noButtonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jLabel5.setText("Tic Tac Toe!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(yesButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(noButton))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(winnerField))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(playerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(playerTurnField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(5, 5, 5))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(button12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(button4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(button8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel5)))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button8, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button9, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button10, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button11, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button12, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button13, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button14, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button15, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(playerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(playerTurnField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(winnerField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(yesButton)
                    .addComponent(noButton))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActionPerformed
        if ( (boardInfo.charAt(0) ==  boardInfo.charAt(1)) && (boardInfo.charAt(2) == 'N') ){ // button controller for button 1
          boardInfo = boardInfo.substring(0,2) + boardInfo.charAt(0) + boardInfo.substring(3);
          player.playerMadeSelection(boardInfo);
       }
    }//GEN-LAST:event_buttonActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        if ( (boardInfo.charAt(0) ==  boardInfo.charAt(1)) && (boardInfo.charAt(3) == 'N') ){ // button controller for button 1
          boardInfo = boardInfo.substring(0,3) + boardInfo.charAt(0) + boardInfo.substring(4);
          player.playerMadeSelection(boardInfo);
       }
    }//GEN-LAST:event_button1ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        if ( (boardInfo.charAt(0) ==  boardInfo.charAt(1)) && (boardInfo.charAt(4) == 'N') ){ // button controller for button 1
          boardInfo = boardInfo.substring(0,4) + boardInfo.charAt(0) + boardInfo.substring(5);
          player.playerMadeSelection(boardInfo);
       }
    }//GEN-LAST:event_button2ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        if ( (boardInfo.charAt(0) ==  boardInfo.charAt(1)) && (boardInfo.charAt(5) == 'N') ){ // button controller for button 1
          boardInfo = boardInfo.substring(0,5) + boardInfo.charAt(0) + boardInfo.substring(6);
          player.playerMadeSelection(boardInfo);
       }
    }//GEN-LAST:event_button3ActionPerformed

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
        if ( (boardInfo.charAt(0) ==  boardInfo.charAt(1)) && (boardInfo.charAt(6) == 'N') ){ // button controller for button 1
          boardInfo = boardInfo.substring(0,6) + boardInfo.charAt(0) + boardInfo.substring(7);
          player.playerMadeSelection(boardInfo);
       }
    }//GEN-LAST:event_button4ActionPerformed

    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed
        if ( (boardInfo.charAt(0) ==  boardInfo.charAt(1)) && (boardInfo.charAt(7) == 'N') ){ // button controller for button 1
          boardInfo = boardInfo.substring(0,7) + boardInfo.charAt(0) + boardInfo.substring(8);
          player.playerMadeSelection(boardInfo);
       }
    }//GEN-LAST:event_button5ActionPerformed

    private void button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button6ActionPerformed
        if ( (boardInfo.charAt(0) ==  boardInfo.charAt(1)) && (boardInfo.charAt(8) == 'N') ){ // button controller for button 1
          boardInfo = boardInfo.substring(0,8) + boardInfo.charAt(0) + boardInfo.substring(9);
          player.playerMadeSelection(boardInfo);
       }
    }//GEN-LAST:event_button6ActionPerformed

    private void button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button7ActionPerformed
        if ( (boardInfo.charAt(0) ==  boardInfo.charAt(1)) && (boardInfo.charAt(9) == 'N') ){ // button controller for button 1
          boardInfo = boardInfo.substring(0,9) + boardInfo.charAt(0) + boardInfo.substring(10);
          player.playerMadeSelection(boardInfo);
       }
    }//GEN-LAST:event_button7ActionPerformed

    private void button8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button8ActionPerformed
        if ( (boardInfo.charAt(0) ==  boardInfo.charAt(1)) && (boardInfo.charAt(10) == 'N') ){ // button controller for button 1
          boardInfo = boardInfo.substring(0,10) + boardInfo.charAt(0) + boardInfo.substring(11);
          player.playerMadeSelection(boardInfo);
       }
    }//GEN-LAST:event_button8ActionPerformed

    private void button9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button9ActionPerformed
        if ( (boardInfo.charAt(0) ==  boardInfo.charAt(1)) && (boardInfo.charAt(11) == 'N') ){ // button controller for button 1
          boardInfo = boardInfo.substring(0,11) + boardInfo.charAt(0) + boardInfo.substring(12);
          player.playerMadeSelection(boardInfo);
       }
    }//GEN-LAST:event_button9ActionPerformed

    private void button10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button10ActionPerformed
        if ( (boardInfo.charAt(0) ==  boardInfo.charAt(1)) && (boardInfo.charAt(12) == 'N') ){ // button controller for button 1
          boardInfo = boardInfo.substring(0,12) + boardInfo.charAt(0) + boardInfo.substring(13);
          player.playerMadeSelection(boardInfo);
       }
    }//GEN-LAST:event_button10ActionPerformed

    private void button11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button11ActionPerformed
        if ( (boardInfo.charAt(0) ==  boardInfo.charAt(1)) && (boardInfo.charAt(13) == 'N') ){ // button controller for button 1
          boardInfo = boardInfo.substring(0,13) + boardInfo.charAt(0) + boardInfo.substring(14);
          player.playerMadeSelection(boardInfo);
       }
    }//GEN-LAST:event_button11ActionPerformed

    private void button12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button12ActionPerformed
        if ( (boardInfo.charAt(0) ==  boardInfo.charAt(1)) && (boardInfo.charAt(14) == 'N') ){ // button controller for button 1
          boardInfo = boardInfo.substring(0,14) + boardInfo.charAt(0) + boardInfo.substring(15);
          player.playerMadeSelection(boardInfo);
       }
    }//GEN-LAST:event_button12ActionPerformed

    private void button13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button13ActionPerformed
        if ( (boardInfo.charAt(0) ==  boardInfo.charAt(1)) && (boardInfo.charAt(15) == 'N') ){ // button controller for button 1
          boardInfo = boardInfo.substring(0,15) + boardInfo.charAt(0) + boardInfo.substring(16);
          player.playerMadeSelection(boardInfo);
       }
    }//GEN-LAST:event_button13ActionPerformed

    private void button14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button14ActionPerformed
        if ( (boardInfo.charAt(0) ==  boardInfo.charAt(1)) && (boardInfo.charAt(16) == 'N') ){ // button controller for button 1
          boardInfo = boardInfo.substring(0,16) + boardInfo.charAt(0) + boardInfo.substring(17);
          player.playerMadeSelection(boardInfo);
       }
    }//GEN-LAST:event_button14ActionPerformed

    private void button15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button15ActionPerformed
        if ( (boardInfo.charAt(0) ==  boardInfo.charAt(1)) && (boardInfo.charAt(17) == 'N') ){ // button controller for button 1
          boardInfo = boardInfo.substring(0,17) + boardInfo.charAt(0) + boardInfo.substring(18);
          player.playerMadeSelection(boardInfo);
       }
    }//GEN-LAST:event_button15ActionPerformed

    private void yesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesButtonActionPerformed
        if (  "XX".equals(boardInfo.substring(0,2)) ){ 
          boardInfo = boardInfo.substring(0,21) + "Y" + boardInfo.charAt(22);
          player.playerMadeSelection(boardInfo);
        } 
        
        if ( "OO".equals(boardInfo.substring(0,2)) ) {
           boardInfo = boardInfo.substring(0,21) + boardInfo.charAt(21) + "Y";
           player.playerMadeSelection(boardInfo);
       }
    }//GEN-LAST:event_yesButtonActionPerformed

    private void noButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noButtonActionPerformed
        if (  "XX".equals(boardInfo.substring(0,2)) ){ 
            boardInfo = boardInfo.substring(0,21) + "N" + boardInfo.charAt(22);
            player.playerMadeSelection(boardInfo);
            winnerField.setText("Game Over. Thanks for playing!");
        } 
        
        if ( "OO".equals(boardInfo.substring(0,2)) ) {
            boardInfo = boardInfo.substring(0,21) + boardInfo.charAt(21) + "N";
            player.playerMadeSelection(boardInfo);
            winnerField.setText("Game Over. Thanks for playing!");
       }
    }//GEN-LAST:event_noButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicTacToe_Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicTacToe_Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicTacToe_Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicTacToe_Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TicTacToe_Application().setVisible(true);
            }
             
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button;
    private javax.swing.JButton button1;
    private javax.swing.JButton button10;
    private javax.swing.JButton button11;
    private javax.swing.JButton button12;
    private javax.swing.JButton button13;
    private javax.swing.JButton button14;
    private javax.swing.JButton button15;
    private javax.swing.JButton button2;
    private javax.swing.JButton button3;
    private javax.swing.JButton button4;
    private javax.swing.JButton button5;
    private javax.swing.JButton button6;
    private javax.swing.JButton button7;
    private javax.swing.JButton button8;
    private javax.swing.JButton button9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton noButton;
    private javax.swing.JTextField playerTextField;
    private javax.swing.JTextField playerTurnField;
    private javax.swing.JTextField winnerField;
    private javax.swing.JButton yesButton;
    // End of variables declaration//GEN-END:variables

    private String boardInfo;
    private EchoClient player;

    public void updateBoard(String b) {
        boardInfo = b;
        
        playerTextField.setText(String.valueOf(boardInfo.charAt(0)));
        playerTurnField.setText(String.valueOf(boardInfo.charAt(1)));
        
        yesButton.setEnabled(false);
        noButton.setEnabled(false);
        
        // Start Button controls based on user input.
        if (boardInfo.charAt(2) == 'N') {
            button.setText("---");
        } 
        else if (boardInfo.charAt(2) == 'O') {
            button.setText(" O ");
        }
        else { //boardInfo.charAt(2) == 'X'
            button.setText(" X ");
        }

        if (boardInfo.charAt(3) == 'N') {
            button1.setText("---");
        } 
        else if (boardInfo.charAt(3) == 'O') {
            button1.setText(" O ");
        }
        else { //boardInfo.charAt(3) == 'X'
            button1.setText(" X ");
        }

        if (boardInfo.charAt(4) == 'N') {
            button2.setText("---");
        } 
        else if (boardInfo.charAt(4) == 'O') {
            button2.setText(" O ");
        }
        else { //boardInfo.charAt(4) == 'X'
            button2.setText(" X ");
        }

        if (boardInfo.charAt(5) == 'N') {
            button3.setText("---");
        } 
        else if (boardInfo.charAt(5) == 'O') {
            button3.setText(" O ");
        }
        else { //boardInfo.charAt(5) == 'X'
            button3.setText(" X ");
        }

        if (boardInfo.charAt(6) == 'N') {
            button4.setText("---");
        } 
        else if (boardInfo.charAt(6) == 'O') {
            button4.setText(" O ");
        }
        else { //boardInfo.charAt(6) == 'X'
            button4.setText(" X ");
        }

        if (boardInfo.charAt(7) == 'N') {
            button5.setText("---");
        } 
        else if (boardInfo.charAt(7) == 'O') {
            button5.setText(" O ");
        }
        else { //boardInfo.charAt(7) == 'X'
            button5.setText(" X ");
        }

        if (boardInfo.charAt(8) == 'N') {
            button6.setText("---");
        } 
        else if (boardInfo.charAt(8) == 'O') {
            button6.setText(" O ");
        }
        else { //boardInfo.charAt(8) == 'X'
            button6.setText(" X ");
        }

        if (boardInfo.charAt(9) == 'N') {
            button7.setText("---");
        } 
        else if (boardInfo.charAt(9) == 'O') {
            button7.setText(" O ");
        }
        else { //boardInfo.charAt(9) == 'X'
            button7.setText(" X ");
        }

        if (boardInfo.charAt(10) == 'N') {
            button8.setText("---");
        } 
        else if (boardInfo.charAt(10) == 'O') {
            button8.setText(" O ");
        }
        else { //boardInfo.charAt(10) == 'X' 
            button8.setText(" X ");
        }

        if (boardInfo.charAt(11) == 'N') {
            button9.setText("---");
        } 
        else if (boardInfo.charAt(11) == 'O') {
            button9.setText(" O ");
        }
        else { //boardInfo.charAt(11) == 'X'
            button9.setText(" X ");
        }

        if (boardInfo.charAt(12) == 'N') {
            button10.setText("---");
        } 
        else if (boardInfo.charAt(12) == 'O') {
            button10.setText(" O ");
        }
        else { //boardInfo.charAt(12) == 'X'
            button10.setText(" X ");
        }

        if (boardInfo.charAt(13) == 'N') {
            button11.setText("---");
        } 
        else if (boardInfo.charAt(13) == 'O') {
            button11.setText(" O ");
        }
        else { //boardInfo.charAt(13) == 'X'
            button11.setText(" X ");
        }

        if (boardInfo.charAt(14) == 'N') {
            button12.setText("---");
        } 
        else if (boardInfo.charAt(14) == 'O') {
            button12.setText(" O ");
        }
        else { //boardInfo.charAt(14) == 'X'
            button12.setText(" X ");
        }

        if (boardInfo.charAt(15) == 'N') {
            button13.setText("---");
        } 
        else if (boardInfo.charAt(15) == 'O') {
            button13.setText(" O ");
        }
        else { //boardInfo.charAt(15) == 'X'
            button13.setText(" X ");
        }

        if (boardInfo.charAt(16) == 'N') {
            button14.setText("---");
        } 
        else if (boardInfo.charAt(16) == 'O') {
            button14.setText(" O ");
        }
        else { //boardInfo.charAt(16) == 'X'
            button14.setText(" X ");
        }

        if (boardInfo.charAt(17) == 'N') {
            button15.setText("---");
        } 
        else if (boardInfo.charAt(17) == 'O')  {
            button15.setText(" O ");
        }
        else if (boardInfo.charAt(17) == 'X') { //boardInfo.charAt(17) == 'X'
            button15.setText(" X ");
        }  
        // End Button controls based on user input.
        
        if ( boardInfo.charAt(20) == 'X' || boardInfo.charAt(20) == 'O' ) {
            winnerField.setText("Player " + boardInfo.charAt(20) + " wins!");
            yesButton.setEnabled(true);
            noButton.setEnabled(true);
            
        } else if ( boardInfo.charAt(20) == 'T') {
            winnerField.setText("Tie Game!");
            yesButton.setEnabled(true);
            noButton.setEnabled(true);
        }
        else if (boardInfo.charAt(20) == 'X') {
            winnerField.setText("Game Over - thanks for Playing!");
        }
        else {
             winnerField.setText(" ");
        }
    }
}